# -*- coding: utf-8 -*-
"""hello_world

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16nJEzFmC5lQ4F18Tqs72BquzJFz_cPnX
"""

print ("Hello World - Ha ini menarik ini!")